const genres = [
  "Fiction",
  "Novel",
  "Narrative",
  "Genre fiction",
  "Non-fiction",
  "Mystery",
  "Science Fiction",
  "Historical Fiction",
  "Thriller",
  "Romance novel",
  "Horror fiction",
  "Biography",
  "Memoir",
  "Poetry",
  "Review",
  "Short story",
  "Young adult fiction",
  "Literary fiction",
  "Autobiography",
  "Children's literature",
  "Humour",
  "Fantasy",
  "Science fantasy",
  "Suspense",
  "Fairy tale",
  "Crime novel",
  "Historical romance",
  "Essay",
  "Paranormal romance",
  "Graphic novel",
  "Article",
  "Self-help book",
  "Adventure fiction",
  "Satire",
  "Magical Realism",
  "Prose",
  "Detective novel",
  "Myth",
  "Drama",
  "Philosophy",
  "Textbook",
  "Coming-of-age story",
  "Encyclopedia",
  "Dictionary",
  "Picture book",
  "Comic book",
  "Speculative fiction",
  "High fantasy",
  "Chick lit",
  "Fantasy Fiction",
  "Cookbook"
];

module.exports = genres;
